# Generated by Django 5.0.6 on 2024-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0005_alter_asignacionequipo_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='area_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='categoria_descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_antiguedad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tc',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='adscripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombramiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rpe',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
