# Generated by Django 5.0.6 on 2024-08-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0007_rename_nombramiento_empleado_area_adscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='descrpcion_area_t',
            new_name='descripcion_area_t',
        ),
    ]
