# Generated by Django 5.0.6 on 2024-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0008_rename_descrpcion_area_t_empleado_descripcion_area_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipo',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
