# Generated by Django 5.0.6 on 2024-08-26 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0009_alter_asignacionequipo_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipo',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='equipment_inventory.empleado'),
        ),
    ]
