# Generated by Django 5.0.6 on 2024-08-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0010_alter_asignacionequipo_detalles_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacionequipo',
            constraint=models.UniqueConstraint(fields=('empleado', 'equipo'), name='asignacion_unica'),
        ),
    ]
