# Generated by Django 5.0.6 on 2024-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0011_asignacionequipo_asignacion_unica'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacionequipo',
            name='asignacion_unica',
        ),
        migrations.AddConstraint(
            model_name='asignacionequipo',
            constraint=models.UniqueConstraint(fields=('equipo',), name='unique_equipo'),
        ),
    ]
