# Generated by Django 5.0.6 on 2024-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0012_remove_asignacionequipo_asignacion_unica_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacionequipo',
            name='unique_equipo',
        ),
        migrations.AddConstraint(
            model_name='asignacionequipo',
            constraint=models.UniqueConstraint(fields=('empleado', 'equipo'), name='unique_equipo'),
        ),
    ]
