# Generated by Django 5.0.6 on 2024-08-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0013_remove_asignacionequipo_unique_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacionequipo',
            name='unique_equipo',
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='equipment_inventory.inventarioequipo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionequipo',
            constraint=models.UniqueConstraint(fields=('equipo',), name='unique_equipo_asignado'),
        ),
    ]
