# Generated by Django 5.0.6 on 2024-08-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0014_remove_asignacionequipo_unique_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_inventory.empleado'),
        ),
    ]
