# Generated by Django 5.0.6 on 2024-08-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_inventory', '0016_alter_asignacionequipo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tc',
            field=models.CharField(blank=True, choices=[('1', 'Confianza'), ('6', 'Base')], max_length=2, null=True),
        ),
    ]
